### PR TITLE
compat csv

### PR DESCRIPTION
**Pull request by mzgubic**
and fix the docs

### CODE REVIEW

**Comment by mzgubic** [comment]
@rofinn I don't think the Documentation job failure is related, and I can't reproduce locally. Building the docs kind of just hangs after `[ Info: ExpandTemplates: expanding markdown templates.`

**Comment by rofinn** [comment]
Yeah, it's a bug in the AxisKeys printing code. My vote would be to pin the documentation build to Julia LTS which is 1.6 now.

**Comment by mzgubic** [comment]
thanks, looks like the job passes now. good to merge?

**Comment by rofinn** [comment]
Yep, looks good to me. Thanks!

**Pull request merged**
